"""Render an :class:`Inventory` to D2 diagram source.

Produces these diagrams:

* ``network.d2``     — every subnet as a container holding its hosts.
* ``hypervisors.d2`` — each hypervisor as a container holding its VM nodes.
* ``containers.d2``  — each Docker/Podman host holding its container nodes.
* ``subnet-<name>.d2`` — one focused diagram per subnet.

Output is plain D2 text (https://d2lang.com); render to SVG/PNG with the ``d2``
CLI. The renderer is a pure function of the model — no scanning, no I/O beyond
writing the files it is handed a directory for.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..models import Host, HostRole, Inventory, Network

# D2 shape/style per role, so the map is readable at a glance.
_ROLE_STYLE: dict[HostRole, str] = {
    HostRole.HYPERVISOR: "{shape: rectangle; style.fill: \"#dbeafe\"}",
    HostRole.VM: "{shape: rectangle; style.fill: \"#dcfce7\"}",
    HostRole.NETWORK: "{shape: hexagon; style.fill: \"#fef9c3\"}",
    HostRole.NAS: "{shape: cylinder; style.fill: \"#f3e8ff\"}",
    HostRole.CONTAINER: "{shape: rectangle; style.fill: \"#ffedd5\"}",
    HostRole.UNKNOWN: "{shape: rectangle}",
}


def _safe_id(raw: str) -> str:
    """A D2-safe identifier (no dots/colons/spaces)."""
    return re.sub(r"[^A-Za-z0-9_]", "_", raw)


class D2Renderer:
    def render(self, inventory: Inventory, out_dir: str | Path) -> list[Path]:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        written.append(self._write(out / "network.d2", self._network_diagram(inventory)))
        written.append(
            self._write(out / "hypervisors.d2", self._hypervisor_diagram(inventory))
        )
        written.append(
            self._write(out / "containers.d2", self._container_diagram(inventory))
        )
        for net in inventory.networks:
            name = _safe_id(net.name or net.cidr)
            written.append(
                self._write(
                    out / f"subnet-{name}.d2", self._subnet_diagram(inventory, net)
                )
            )
        return written

    # --- diagrams ---------------------------------------------------------
    def _network_diagram(self, inv: Inventory) -> str:
        lines = ["# Network overview — generated by myinventory", ""]
        placed = set()
        for net in inv.networks:
            cid = _safe_id(net.label)
            lines.append(f'{cid}: "{net.label}" {{')
            for host in inv.hosts_in(net):
                lines.append(f"  {self._host_node(host, indent=2)}")
                placed.add(host.id)
            lines.append("}")
            lines.append("")

        orphans = [h for h in inv.hosts.values() if h.id not in placed]
        if orphans:
            lines.append('unassigned: "Unassigned" {')
            for host in orphans:
                lines.append(f"  {self._host_node(host, indent=2)}")
            lines.append("}")
        return "\n".join(lines).rstrip() + "\n"

    def _subnet_diagram(self, inv: Inventory, net: Network) -> str:
        lines = [f"# Subnet {net.label} — generated by myinventory", ""]
        for host in inv.hosts_in(net):
            lines.append(self._host_node(host, indent=0))
        return "\n".join(lines).rstrip() + "\n"

    def _hypervisor_diagram(self, inv: Inventory) -> str:
        lines = ["# Hypervisors and their VMs — generated by myinventory", ""]
        hypervisors = [h for h in inv.hosts.values() if h.is_hypervisor]
        if not hypervisors:
            return "# No hypervisors discovered.\n"

        edges: list[str] = []
        for hyper in hypervisors:
            hid = _safe_id(hyper.id)
            label = hyper.hostname or hyper.primary_address or hyper.id
            lines.append(f'{hid}: "🖥  {label}" {{')
            lines.append("  style.fill: \"#dbeafe\"")
            for vm in inv.vms_of(hyper.id):
                vid = _safe_id(vm.id)
                state = "▶" if vm.power_state.value == "running" else "⏹"
                ip = f"\\n{vm.addresses[0]}" if vm.addresses else ""
                lines.append(
                    f'  {vid}: "{state} {vm.name}{ip}" {{shape: rectangle}}'
                )
                # A VM correlated to a network-discovered host gets a cross-link
                # so the map shows the guest is also seen on the network.
                if vm.host_id and vm.host_id in inv.hosts:
                    edges.append(
                        f'{hid}.{vid} -> {_safe_id(vm.host_id)}: "on network"'
                    )
            lines.append("}")
            lines.append("")

        if edges:
            lines.append("# VM ↔ network-discovered host cross-links")
            lines.extend(edges)
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _container_diagram(self, inv: Inventory) -> str:
        lines = ["# Container hosts and their containers — generated by myinventory", ""]
        hosts = [h for h in inv.hosts.values() if h.containers]
        if not hosts:
            return "# No containers discovered.\n"

        for host in hosts:
            hid = _safe_id(host.id)
            label = host.hostname or host.primary_address or host.id
            runtime = host.extra.get("container_runtime", "docker")
            lines.append(f'{hid}: "🐳 {label} ({runtime})" {{')
            lines.append("  style.fill: \"#dbeafe\"")
            for ctr in host.containers:
                cid = _safe_id(f"{host.id}-{ctr.id or ctr.name}")
                state = "▶" if ctr.is_running else "⏹"
                img = f"\\n{ctr.image}" if ctr.image else ""
                lines.append(
                    f'  {cid}: "{state} {ctr.name}{img}" '
                    f"{_ROLE_STYLE[HostRole.CONTAINER]}"
                )
            lines.append("}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    # --- nodes ------------------------------------------------------------
    @staticmethod
    def _host_node(host: Host, indent: int) -> str:
        nid = _safe_id(host.id)
        label = host.hostname or host.primary_address or host.id
        svc = ""
        if host.services:
            names = ", ".join(sorted({s.name or s.key for s in host.services})[:4])
            svc = f"\\n{names}"
        style = _ROLE_STYLE.get(host.role, _ROLE_STYLE[HostRole.UNKNOWN])
        return f'{nid}: "{label}{svc}" {style}'

    @staticmethod
    def _write(path: Path, content: str) -> Path:
        path.write_text(content)
        return path
