"""Render an :class:`Inventory` to D2 diagram source.

Produces these diagrams:

* ``network.d2``     — every subnet as a container holding its hosts.
* ``hypervisors.d2`` — each hypervisor as a container holding its VM nodes.
* ``containers.d2``  — each Docker/Podman host holding its container nodes.
* ``subnet-<name>.d2`` — one focused diagram per subnet.

Output is plain D2 text (https://d2lang.com); render to SVG/PNG with the ``d2``
CLI. The renderer is a pure function of the model — no scanning, no I/O beyond
writing the files it is handed a directory for.
"""

from __future__ import annotations

import math
import re
from pathlib import Path

from ..models import Host, HostRole, Inventory, Network

# D2 shape/style per role, so the map is readable at a glance.
_ROLE_STYLE: dict[HostRole, str] = {
    HostRole.HYPERVISOR: "{shape: rectangle; style.fill: \"#dbeafe\"}",
    HostRole.VM: "{shape: rectangle; style.fill: \"#dcfce7\"}",
    HostRole.NETWORK: "{shape: hexagon; style.fill: \"#fef9c3\"}",
    HostRole.NAS: "{shape: cylinder; style.fill: \"#f3e8ff\"}",
    HostRole.PRINTER: "{shape: page; style.fill: \"#fee2e2\"}",
    HostRole.CONTAINER: "{shape: rectangle; style.fill: \"#ffedd5\"}",
    HostRole.UNKNOWN: "{shape: rectangle}",
}


def _safe_id(raw: str) -> str:
    """A D2-safe identifier (no dots/colons/spaces)."""
    return re.sub(r"[^A-Za-z0-9_]", "_", raw)


def _grid_columns(count: int) -> int:
    """Pick a column count so unconnected children wrap into a tidy grid.

    Without this, D2's default layout packs edge-less nodes into a single
    cramped row. Aim for a roughly square grid, capped so wide hosts stay
    readable.
    """
    if count <= 1:
        return 1
    return min(4, math.ceil(math.sqrt(count)))


class D2Renderer:
    def render(self, inventory: Inventory, out_dir: str | Path) -> list[Path]:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        written.append(self._write(out / "network.d2", self._network_diagram(inventory)))
        written.append(
            self._write(out / "hypervisors.d2", self._hypervisor_diagram(inventory))
        )
        written.append(
            self._write(out / "containers.d2", self._container_diagram(inventory))
        )
        for net in inventory.networks:
            name = _safe_id(net.name or net.cidr)
            written.append(
                self._write(
                    out / f"subnet-{name}.d2", self._subnet_diagram(inventory, net)
                )
            )
        return written

    # --- diagrams ---------------------------------------------------------
    def _network_diagram(self, inv: Inventory) -> str:
        lines = [
            "# Network overview — generated by myinventory",
            f"grid-columns: {_grid_columns(len(inv.networks) + 1)}",
            "",
        ]
        placed = set()
        for net in inv.networks:
            cid = _safe_id(net.label)
            members = inv.hosts_in(net)
            lines.append(f'{cid}: "{net.label}" {{')
            lines.append(f"  grid-columns: {_grid_columns(len(members))}")
            for host in members:
                lines.append(f"  {self._host_node(host, indent=2)}")
                placed.add(host.id)
            lines.append("}")
            lines.append("")

        orphans = [h for h in inv.hosts.values() if h.id not in placed]
        if orphans:
            lines.append('unassigned: "Unassigned" {')
            lines.append(f"  grid-columns: {_grid_columns(len(orphans))}")
            for host in orphans:
                lines.append(f"  {self._host_node(host, indent=2)}")
            lines.append("}")
        return "\n".join(lines).rstrip() + "\n"

    def _subnet_diagram(self, inv: Inventory, net: Network) -> str:
        members = inv.hosts_in(net)
        lines = [
            f"# Subnet {net.label} — generated by myinventory",
            f"grid-columns: {_grid_columns(len(members))}",
            "",
        ]
        for host in members:
            lines.append(self._host_node(host, indent=0))
        return "\n".join(lines).rstrip() + "\n"

    def _hypervisor_diagram(self, inv: Inventory) -> str:
        hypervisors = [h for h in inv.hosts.values() if h.is_hypervisor]
        if not hypervisors:
            return "# No hypervisors discovered.\n"

        lines = [
            "# Hypervisors and their VMs — generated by myinventory",
            "# A green VM is also seen as a host on the network.",
            f"grid-columns: {_grid_columns(len(hypervisors))}",
            "",
        ]
        for hyper in hypervisors:
            hid = _safe_id(hyper.id)
            label = hyper.hostname or hyper.primary_address or hyper.id
            vms = inv.vms_of(hyper.id)
            lines.append(f'{hid}: "🖥  {label}" {{')
            lines.append("  style.fill: \"#dbeafe\"")
            if vms:
                lines.append(f"  grid-columns: {_grid_columns(len(vms))}")
            else:
                lines.append('  empty: "(no VMs discovered)" {style.opacity: 0.6}')
            for vm in vms:
                vid = _safe_id(vm.id)
                state = "▶" if vm.power_state.value == "running" else "⏹"
                ip = f"\\n{vm.addresses[0]}" if vm.addresses else ""
                # A VM correlated to a network-discovered host is filled green so
                # the map shows at a glance the guest is also seen on the network.
                on_net = bool(vm.host_id and vm.host_id in inv.hosts)
                fill = "#dcfce7" if on_net else "#f1f5f9"
                lines.append(
                    f'  {vid}: "{state} {vm.name}{ip}" '
                    f'{{shape: rectangle; style.fill: "{fill}"}}'
                )
            lines.append("}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _container_diagram(self, inv: Inventory) -> str:
        hosts = [h for h in inv.hosts.values() if h.containers]
        if not hosts:
            return "# No containers discovered.\n"
        lines = [
            "# Container hosts and their containers — generated by myinventory",
            f"grid-columns: {_grid_columns(len(hosts))}",
            "",
        ]

        for host in hosts:
            hid = _safe_id(host.id)
            label = host.hostname or host.primary_address or host.id
            runtime = host.extra.get("container_runtime", "docker")
            lines.append(f'{hid}: "🐳 {label} ({runtime})" {{')
            lines.append("  style.fill: \"#dbeafe\"")
            lines.append(f"  grid-columns: {_grid_columns(len(host.containers))}")
            for ctr in host.containers:
                cid = _safe_id(f"{host.id}-{ctr.id or ctr.name}")
                state = "▶" if ctr.is_running else "⏹"
                img = f"\\n{ctr.image}" if ctr.image else ""
                lines.append(
                    f'  {cid}: "{state} {ctr.name}{img}" '
                    f"{_ROLE_STYLE[HostRole.CONTAINER]}"
                )
            lines.append("}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    # --- nodes ------------------------------------------------------------
    @staticmethod
    def _host_node(host: Host, indent: int) -> str:
        nid = _safe_id(host.id)
        label = host.hostname or host.primary_address or host.id
        svc = ""
        if host.services:
            names = ", ".join(sorted({s.name or s.key for s in host.services})[:4])
            svc = f"\\n{names}"
        style = _ROLE_STYLE.get(host.role, _ROLE_STYLE[HostRole.UNKNOWN])
        return f'{nid}: "{label}{svc}" {style}'

    @staticmethod
    def _write(path: Path, content: str) -> Path:
        path.write_text(content)
        return path
